### ISSUE TITLE
[Feature] Please support multi window like easymotion

### ISSUE THREAD

**Issue by fgheng** [phaazon/hop.nvim#10]

**Comment by phaazon** [comment]
I have an idea on how to do that and that shouldn’t be too hard. I’ll try to see if I can work on that later in the week.

**Comment by phaazon** [comment]
This should be doable at some point with minimal effort, but I don’t plan to work on this for now as there are a bunch of PRs waiting for reviews and some bugs left to fix. I’ll put that in a _next-batch_ to do later.

**Comment by phaazon** [comment]
So I gave it a try yesterday and today and turns out, even though Hop’s API is rather simple to extend to support that, Neovim’s internals suffer from exposing a nice API to do the width calculation. [Example here](https://github.com/phaazon/hop.nvim/blob/master/lua/hop/init.lua#L80-L86). Because when the user sets `wrap` Neovim will display a whole line in the buffer (possible on several terminal lines), we know we need to hint a line completely, but with `nowrap`, a line will basically be cut off, requiring us to truncate the line starting from `leftcol` up to the width of the visible part of the buffer, information that is currently impossible to get from Neovim without the hack mentioned above.

The problem is that that hack relies on a super ugly window-dependent view manipulation (only for the current window). And it’s enough of a big hack to add more.

There might be solutions to this problem (probably new APIs I’m not aware of), but for now, it looks like this feature is hitting a hard stop.
