### ISSUE TITLE
Cannot map to predefined Pattern

### ISSUE THREAD

**Issue by iago-lito** [phaazon/hop.nvim#105]
This naive addition to my `.vimrc` does not work as expected:
```vimscript
nnoremap tD :HopPattern<cr>\d<cr>
```
When I hit `tD` in normal mode, I'm still getting the interactive prompt for a pattern. And when I'm done re-hitting `\d` by hand, then `\d` seems gets executed as a vim normal mode.

How can I map `HopPattern(AC|BC)?` to such a fixed predefined pattern?

**Comment by phaazon** [comment]
That’s a good question. You probably have several choices here:

- Use the Lua API to implement that function on your side.
- Use an input-list plugin, like fzf, telescope, etc., to feed the function from the previous point.
- Find a way to issue input keystrokes after starting a command, which I have no idea how to do nor whether it’s possible.

**Comment by iago-lito** [comment]
Okay, thanks :)

> - Use the Lua API to implement that function on your side.

I have never used the Lua API or lua in general. Does it end up as some oneliner `lua <mumblemumble>hop.hintpattern("\d")` in my `.vimrc`? Or is it more engaged with some separate lua file?

> - Use an input-list plugin, like fzf, telescope, etc., to feed the function from the previous point.

I'm sorry I'm unfamiliar with these plugins and what they do exactly :\

> - Find a way to issue input keystrokes after starting a command, which I have no idea how to do nor whether it’s possible.

I'm happy to look into it, do you think `keystroke after command` are the only keywords I need? I'm not sure what's the technique you use for capturing user input after they issued `HopChar1`. But for sure if the mapped keys were captured the same way, then `nnoremap tD :HopPattern<cr>\d<cr>` would work smoothly as expected :)

(.. unless you meant *emulating* the keystrokes with `e.g.` external call to [`xte`](https://linux.die.net/man/1/xte)?)

**Comment by phaazon** [comment]
> I have never used the Lua API or lua in general. Does it end up as some oneliner lua <mumblemumble>hop.hintpattern("\d") in my .vimrc? Or is it more engaged with some separate lua file?

Yes, it would mean this. But currently, that kind of hint is not supported. However… now that I think about it, it should be rather super simple to extend the `hint_pattern` with an optional argument that, if `nil`, would default to the current behavior (i.e. user input), and if present, would just jump to that pattern.

> I'm sorry I'm unfamiliar with these plugins and what they do exactly :\

Most of them are fuzzy finders, and some even generic ones, used to basically provide a listing framework for users. You can then ask the user to pick 1 to N entries in a list (that you can fuzzy search)… list provided by the plugin / yourself. I personally use that a lot in my terminal with fzf (for instance, I basically have a `gs` script, allowing to quickly switch git branches, that does `git branch | fzf | git switch`.

For the third option, I think you’re going to have a hard time, because I think it’s not really trivial. Emulating the keystrokes could be possible but it would fall in off scope of Hop. There is a way to feed keys to neovim (`:h nvim_feedkeys`), but not sure how we could use that _after_ calling `hint_pattern` :confused:

**Comment by iago-lito** [comment]
> now that I think about it, it should be rather super simple to extend the `hint_pattern` with an optional argument that, if nil, would default to the current behavior (i.e. user input), and if present, would just jump to that pattern.

Yeah cool, why not :) The only thing left would be to expose `hint_pattern` API to user? Or is it already the case?

> Most of them are fuzzy finders

Oh, so you were suggesting to just use my previous searched pattern history to reach back to `\d`?

> Emulating the keystrokes could be possible but it would fall in off scope of Hop.

That's my opinion too, I would have been very reluctant to get along with keyboard emulation anyway :P

**Comment by iago-lito** [comment]
Fixed in #112. Thanks for merging ;)
