### ISSUE TITLE
`HopLine` takes a full second to display hints

### ISSUE THREAD

**Issue by Alekhine51** [phaazon/hop.nvim#132]
My binding is `vim.api.nvim_set_keymap('n', 'g', "<cmd>lua require'hop'.hint_lines()<cr>", {})`. For some reason this takes a full second, maybe even a second and a half, to display hints, whereas `hint_words` is instant.

**Comment by Alekhine51** [comment]
So, this has something to do with the fact that it's bound to `g`. Binding it to `f` works fine, so I guess binding it to motions is simpler. I think what nvim does (semi-beginner) is put the char in a buffer at the bottom right because it expects something to come after that, so it takes a second for the command to 'come through'.

**Comment by donkeyboy666** [comment]
timeoutlen

**Comment by ggandor** [comment]
@donkeyboy666 This was probably very helpful for a self-proclaimed "semi-beginner" :P

@Alekhine51 Yep, this is because there are mappings that _start_ with `g` (there are a bunch of native commands, e.g. `gv`, `gn`, etc.), so Vim has to wait for some time to allow you to complete the mapping - the length of this can be configured via the `timeoutlen` option (see `:h timeout`, `:h ttimeout`, `:h timeoutlen`, `:h ttimeoutlen`). But for this reason, it is not a good idea to map anything to `g` after all.

**Comment by phaazon** [comment]
Yes, I suggest tweaking your `timeoutlen` variable (I personally set it to `0`).
