### ISSUE TITLE
Allow to set configuration with a setup function

### ISSUE THREAD

**Issue by weilbith** [phaazon/hop.nvim#19]
Hey, thanks for this great plugin. After EasyMotion is just not usable with language servers in combo, I was desperately searching an alternative, but nothing has fit until now. Thanks. :pray: 

In the docs you have a section for some configurations. Unfortunately it seems like you can only provide those values only to the low level API calls. I rather use the Vim commands which I also use to lazy load this plugin. It would be cool if there is a setup like function (as many Lua plugins use) to provide your own default for these configuration values.

**Comment by phaazon** [comment]
Yep! I want to do this, but so far I haven’t really looked into it too much. I noticed that `setup` function everybody uses but… you still have to provide the configuration in Lua, right?

**Comment by weilbith** [comment]
> you still have to provide the configuration in Lua, right?

What do you mean? :thinking:
That this would be then a Lua function call? That would be fine for me. It's the same for all other plugins as well. :shrug:

**Comment by phaazon** [comment]
I mean, the `setup` function lives in lua, no? How do you configure it? What I currently have on my mind:

- Keep the current (lua) functions taking the `opts` options arguments. If it’s passed, it overrides settings in those functions.
- Add a `setup(opts)` function, allowing people to set the configuration for the plugin.
- All the commands like `:HopWord` will call the lua function as they currently do (i.e. without setting `opts`). If you called `setup`, your options will be used by those commands.

Would that be okay to you? :)

**Comment by phaazon** [comment]
This is now implemented. Can you give it a try and tell me whether it fixes your issue? :)

**Comment by jose-elias-alvarez** [comment]
I'm not sure if this was intentional, but this change made it so that Hop commands no longer work without an empty setup function, e.g. `require"hop".setup {}`. Poking around the code, I think I can see why (using `hint_words` as an example):

https://github.com/phaazon/hop.nvim/blob/be919d61d4136d2092f42c922f545bb8c8723fb8/lua/hop/init.lua#L175

If `setup` isn't explicitly called, both opts and M.opts will be `nil` when called.

If this was intentional, it'd be nice to mention it in the readme to avoid confusion. If not, I was able to hack together a simple solution, so let me know if you'd like me to submit a PR (or if you just want to take care of it yourself). Either way, thanks for the work on the plugin!

**Comment by weilbith** [comment]
> This is now implemented. Can you give it a try and tell me whether it fixes your issue? :)

Thank you very much. I tested it and it works. :upside_down_face: 

> I'm not sure if this was intentional, but this change made it so that Hop commands no longer work without an empty setup function,

I can confirm that this is buggy. After I just did the update my old mappings where broken until I added the setup function call. I would assume that the plugin should still work, also without setup. Shouldn't it?

**Comment by phaazon** [comment]
A fix was merged for this. Indeed it broke default commands if no `setup` was there, but it should work now. Sorry for the inconvenience.
