### ISSUE TITLE
`t` like motions

### ISSUE THREAD

**Issue by xeluxee** [phaazon/hop.nvim#191]
Hi, thanks for this useful plugin

I'm trying to reproduce `t` behavior with hop, but I can't make the landing position precede the given character. I've played with `inclusive_jump` option, but I can't get it to work.
``` lua
vim.api.nvim_set_keymap('', 't', "<cmd>lua require'hop'.hint_char1({ direction = require'hop.hint'.HintDirection.AFTER_CURSOR, current_line_only = true, inclusive_jump = false })<cr>", {})
```

**Comment by phaazon** [comment]
Currently, this only works with operator-pending. I will make an update to make it possible in any mode.

**Comment by ouuan** [comment]
In #192:
> The name of the feature is misleading indeed. I will probably switch to the other design I had intended first (offset), so that every possibility can be implemented (in operator-pending mode, but also any other mode).

That's a solution. And I think we should provide some presets for `f`/`t`-like motions, which can be based on different settings of the offset.

**Comment by ldelossa** [comment]
Hello,

Came here because I too was using "t" and expected the cursor to stop just before the character I was searching. 

I see some movement on this issue, but a little confused about what to expect moving forward. 

Will we see a PR which makes everything "just work" soon? I.e. I have the suggested key maps from the readme in my config. If I sit tight and just keep updating hop.nvim will the "t" functionality just work eventually, or will changes to my config be necessary? 

Just asking so I can keep an eye on when I may see this work.

**Comment by phaazon** [comment]
This is now possible.

```
:h hop-config-hint_offset
```
