### ISSUE TITLE
Visual Mode

### ISSUE THREAD

**Issue by chmln** [phaazon/hop.nvim#28]
Hey, really enjoying flying around the buffer with hop.

It would be great to be able to hop in visual mode to make faster selections.
Currently it just exits the visual mode upon execution.

**Comment by darzok0914** [comment]
When talking phaazon on twitch he mentioned this feature so I guess it should be in the pipeline

**Comment by phaazon** [comment]
This is now fix. Please tell me whether it resolves your issues so that we can close this issue. You can give it a test by binding the `<cmd>HopWordVisual<cr>` to a key in visual mode (`x`) for instance. It is possible to enable this behavior by default for regular commands (e.g. `HopWord`) but requires to set the `extend_visual` option to `true` in your conf.

:beers:

**Comment by chmln** [comment]
This is perfect. I love it. Thank you @phaazon

**Comment by bscuron19** [comment]
Sorry if this seems like a simple question, but how do I get the updated files with the visual extend changes? I used vim plug in my init.vim to download the plugin, but it does not have the new changes. 

Thanks for your help.

**Comment by phaazon** [comment]
@bscuron19 when did you update it? Normally, you should only have to `:PlugUpdate`, then make a mapping for hop in visual mode (I actually use a mapping for all mode but insert mode for that).

**Comment by bscuron19** [comment]
@phaazon  I got it now, I looked through the commits and noticed you removed the HopWordVisual and combined it into the normal functionality. Thanks!
