### ISSUE TITLE
[BUG] Invalid 'col': out of range

### ISSUE THREAD

**Issue by linrongbin16** [phaazon/hop.nvim#361]
Hi, I'm using `HopChar1AC` to jump forward, but there's an exception `Invalid 'col': out of range`:

<img width="1920" alt="image" src="https://user-images.githubusercontent.com/6496887/236173591-398ef1ab-9e7d-4da4-a9c2-443f5ae66069.png">

It's happening on [a specific file](https://github.com/linrongbin16/lin.nvim.dev/blob/f5ae98fb54eff785abd51549730d2debe52e0155/docs/introduction/feature.md#L1), not on every file.

**Comment by nikolasetiawan** [comment]
Experiencing the same issue. For me, this happens when initiating `hint_char1` from an empty line. It shows the following error:
```
Invalid 'col': out of range
```

**Comment by BartSte** [comment]
> Experiencing the same issue. For me, this happens when initiating `hint_char1` from an empty line. It shows the following error:
> 
> ```
> Invalid 'col': out of range
> ```

Possible duplicate from #335. I had the same issue. Ah PR was made by someone but it is not merged, unfortunately.

**Comment by prss-ad** [comment]
HI, 
I'm having the same problem . From what i gathered, it happens when on an empty line as reported. But i can also say it only happens when hint.direction is set and current_line_only is false.

-- this works flawlessly even with multiwindows
vim.keymap.set({ 'n', 'x' }, '<leader>j', function()    require('hop').hint_char1()
end)
-- but this does not (same for F,t,T) , --- Invalid col : out of range
vim.keymap.set({ 'n', 'x' }, 'f', function()
    require('hop').hint_char1({
        direction = require('hop.hint').HintDirection.AFTER_CURSOR,
        current_line_only = false
    })
end)

Hope this helps a bit.
Thanks for this plugin .
It's great.

**Comment by theofabilous** [comment]
There's a pull request (#358) that fixes this issue, it's been open for a while. Personally I added:
```lua
  if #vim.api.nvim_get_current_line() == 0 then
    cursor_pos[2] = cursor_pos[2] - 1
  end
```
after line 92 in `init.lua` and it fixed the problem

**Comment by prss-ad** [comment]
Thanks theofabilous ! That works, missed the pull request...

**Comment by yingmanwumen** [comment]
hello, there's another PR #363 fix this bug, and it works on my machine
