### ISSUE TITLE
How to combine motion with yanking & deleting?

### ISSUE THREAD

**Issue by zartstrom** [phaazon/hop.nvim#38]
Movement with hop works excellent and I use ie. this key binding:
`map <Space>w :HopWord<CR>`

Now lets say I want to yank (likewise for delete) until a certain word, fot that I would like to use:
`y<Space>w` + `target character`, but that result just in a movement with my register unchanged.

How to combine then motion with yanking (deleting), is it possible? Is there a better then above way to do the key binding?

Thanks a lot for the effort you put into this plugin.

**Comment by phaazon** [comment]
Honestly, I’ve been looking to do that for a while. It’s implemented for selection (you can go in any visual mode and hop to extend the selection), but Hop is not a motion by itself.

I need to talk with other neovim contributors to see how I could make Hop a motion, so that we can combine it with `y`, `c`, `d`, etc.

**Comment by phaazon** [comment]
Okay, I have found a way. I’ll make that change tonight because it would be super neat to use Hop like that!

**Comment by peterrus** [comment]
Hi @phaazon, Could maybe explain how to use this? Maybe I am just doing it wrong:

In my init.vim I have: `nmap s :HopChar2<CR>` (Could have done this with lua using `lua vim.api.nvim_set_keymap('n', 's', "<cmd>lua require'hop'.hint_char2()<cr>", {})` but that makes no difference.

Then I want to yank until `hi`, so I do `yshi`. Is that the wrong way to do this? Because nothing is happening.

**Comment by ggandor** [comment]
@peterrus You just forgot to use `omap` instead of `nmap`, for operator-pending mode :)

**Comment by peterrus** [comment]
@ggandor Thanks for the swift reply (:

I created the following mapping:

```
nmap s :HopChar2<CR>
omap s :HopChar2
```
(Also with a <CR> after the omap, but that didn't make a difference).

But it feels like vim is not going into 'hop mode'. Am I still doing it wrong?

**Comment by ggandor** [comment]
@peterrus I get it now, `-noremap` should be used, it will work that way.

**Comment by peterrus** [comment]
@ggandor I am afraid it still doesn't do anything:

```
nmap s :HopChar2<CR>
onoremap s :HopChar2<CR>
```
Do I maybe need to call something else instead of `:HopChar2`, you sometimes see these `<Plug>` calls or `hop#whatever()` calls. I am not very well versed in (neo)vim internals so this going a bit above my ahead currently.

**Comment by ggandor** [comment]
@peterrus This is very interesting, it indeed doesn't work, just tried it. Some keys work, I tried `b`, and that's fine. `s` or `o` doesn't work, for example. (I `umap`ped each before mapping them to Hop.) I don't see the pattern yet.
