### ISSUE TITLE
Go to next/previous match using n and N

### ISSUE THREAD

**Issue by bscuron19** [phaazon/hop.nvim#46]
Is it possible to use **n** to go to next match (of the pattern search) and **N** to go to the match above in the document?

Here is an example of what I mean using EasyMotion.

![vim](https://user-images.githubusercontent.com/29784485/111081268-d9fd7180-84d8-11eb-8f04-3924443b426b.gif)

Thanks for your help!

**Comment by phaazon** [comment]
You mean after quitting it? So you basically want that quitting the pattern mode is the same as `/`, right?

**Comment by bscuron19** [comment]
> You mean after quitting it? So you basically want that quitting the pattern mode is the same as `/`, right?

Yes exactly

**Comment by bscuron19** [comment]
also if there are no matches on the screen, but there are matches in the document, n would still take you to the next match

**Comment by monkoose** [comment]
@phaazon Personally i against it. I looked for simpler/faster/diagnostics friendly replacement of EasyMotion, and i found it.
Thank you for your work. And keep it simple as much as possible please, such requests for implementing some staff, that this plugin is not about, will popup a lot.

@bscuron19 Why do you want to merge such thing like full search and `thing` that just jump to any position on the screen in the same plugin? Why just not `/searchpattern` if you need something that are not on the screen?

**Comment by bscuron19** [comment]
@monkoose I actually agree with you. Since posting this issue I learned of the use of the asterisk in vim (search word under cursor). This takes away the need for hop to automatically fill your search 'buffer' with the pattern matched.

Thanks for your reply!

**Comment by ned-si** [comment]
I would totally love this feature to completely be able to have unify way of search/hopping through a document with a similar UX in all cases.

@monkoose
> Why just not /searchpattern if you need something that are not on the screen?

Because I could totally see myself wanting to hop to a certain pattern with `HopPattern` and then just move around the document's occurrences of that pattern. And no, `*` doesn't replace it at all (it might be used in some specific use-cases, but still, it's not a complete replacement).

@phaazon Any idea if there is a way to make something like this work by doing some configuration magic maybe?

**Comment by ggandor** [comment]
@ned-si Doing it outside the core is not possible without a complicated wrapper function that gets input itself and reinvents the wheel, but if I'm not mistaken, this would be a one-line PR, since all we need to do is to set the search register after accepting the pattern (`vim.fn.setreg('/', <pattern-given-to-HopPattern>)`).

**Comment by huyu398** [comment]
I also need this feature. The lack of this feature is hindering the transition from vim-easymotion to hop.nvim.

**Comment by huyu398** [comment]
@phaazon 
I also need this feature. The lack of this feature is hindering the transition from vim-easymotion to hop.nvim.
