### ISSUE TITLE
Any Example of using hop for word operators?

### ISSUE THREAD

**Issue by JoseConseco** [phaazon/hop.nvim#79]
How do I use / map  hop to be used as word operator (delte, replace tec)? Its mentioned in HOP docs but I'm not sure how to use it.

Can hop be used to extend selection eg we go into visual mode, then hop to given line or word while extending selection?

**Comment by tssm** [comment]
I can confirm Hop works with operators. I have some operator mappings, and all work. For example with:

```
onoremap <silent> rp :lua require'hop'.hint_patterns()<cr>
```

I can type something like `drp<cr>` and Hop will highlight all the options. After selecting one all the text between the previous position and the new one will be deleted.

It should work with selections too, but I cannot get them working. I created some visual mappings like:

```
xnoremap <silent> rp :lua require'hop'.hint_patterns()<cr>
```

But although the cursor moves correctly, the selection disappears instead of being extended. @phaazon am I missing something?

**Comment by JoseConseco** [comment]
Thx for info. I just discovered that we  can use /  or ? to extend visual selection ( eg .    v/test   - will select forward up to word 'test') so I will use build in commands. Still I could be very cool feature in HOP to extend visual selection.

**Comment by davidsierradz** [comment]
I'm also trying to make an operator mapping with `<C-Space>` but doesn't work:
```
onoremap <silent> <C-Space> :lua require'hop'.hint_char1()<cr>
```
I type `d<C-Space>` search for a char and this appears on the command line: ` -> there’s no such thing we can see…`

**Comment by JoseConseco** [comment]
I figured it out finally:
`vim.api.nvim_set_keymap('o', 'c',  ":HopChar1<cr>", {noremap = true})`

The magic is using `o` as target for map. Now  using c- will jump to char1.   Eg now pressing  `dch` will  (delete  - until char1 - h)

**Comment by guilhermeprokisch** [comment]
@JoseConseco  how about yank?

> I figured it out finally: `vim.api.nvim_set_keymap('o', 'c', ":HopChar1<cr>", {noremap = true})`
> 
> The magic is using `o` as target for map. Now using c- will jump to char1. Eg now pressing `dch` will (delete - until char1 - h)

**Comment by JoseConseco** [comment]
quite the same :   
ych   - **y**ank   hop to 'h' letter.   
cch - **c**hange hop to 'h' letter,   
dcx - **d**elte hop to 'x'

**Comment by guilhermeprokisch** [comment]
@JoseConseco ooh yeah. It's working. Thank you!
